In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import koreanize_matplotlib
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

c:\Users\user\miniconda3\envs\this_is_da\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
df = pd.read_csv('data/credit_fraud.csv')
df.head()

account_age_days  transaction_amt  transaction_adj_amt  historic_velocity  \
0            3371.0           2167.0                 56.0             2572.0   
1            2714.0           2045.0                 48.0             4517.0   
2            6987.0           2892.0                 61.0             5007.0   
3            2712.0           3040.0                 28.0             6022.0   
4            3598.0           2976.0                 66.0             2600.0   

       ip_address                                         user_agent  \
0   154.68.49.124  Opera/9.81.(Windows NT 10.0; ht-HT) Presto/2.9...   
1   39.131.125.85  Opera/9.76.(X11; Linux i686; mi-NZ) Presto/2.9...   
2  166.245.194.83  Mozilla/5.0 (X11; Linux x86_64; rv:1.9.6.20) G...   
3   100.1.217.216  Mozilla/5.0 (Macintosh; Intel Mac OS X 10 9_3 ...   
4  113.156.65.245  Mozilla/5.0 (X11; Linux x86_64; rv:1.9.5.20) G...   

         email_domain           phone_number    billing_city  billing_postal  \
0     perez-garza.com           878-111-5140      Woodsburgh         96336.0   
1   mcneil-ortega.com          (002)736-0139      West Kevin         78083.0   
2  davis-calderon.com      (983)585-2863x652     Lorichester         83236.0   
3        rose-lee.org  +1-678-897-3420x60738    Stephenmouth         78364.0   
4            nash.net    (013)204-1766x92641  New Brianmouth         77499.0   

   ... transaction_env      EVENT_TIMESTAMP   applicant_name  \
0  ...               X  2020-12-29 09:05:51     Linda Wright   
1  ...               W  2021-06-22 18:05:06     Terri Rivera   
2  ...               X  2021-05-10 13:48:38       Sarah Gray   
3  ...               N  2021-03-11 07:36:40  Valerie Jenkins   
4  ...               G  2021-03-27 06:13:35      Amy Coleman   

     billing_address  merchant_id  locale tranaction_initiate  \
0  4684 Sharon Ranch  066-82-8795  niu_NZ                   O   
1  7642 Allison Ramp  669-99-9459  apn_IN                   J   
2  4948 Lisa Passage  086-41-1624   dv_MV                   T   
3   1616 Little Camp  669-97-4021  byn_ER                   M   
4   149 Harris Rapid  088-21-6329  the_NP                   K   

  days_since_last_logon inital_amount EVENT_LABEL  
0                  59.0       13646.0       legit  
1                   0.0       11930.0       legit  
2                  83.0        7412.0       legit  
3                  24.0        4623.0       legit  
4                  21.0        1905.0       legit  

[5 rows x 26 columns]

# 데이터 EDA & 전처리

## 기본 정보

In [10]:
df.shape

(150000, 26)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   account_age_days       149892 non-null  float64
 1   transaction_amt        149870 non-null  float64
 2   transaction_adj_amt    149886 non-null  float64
 3   historic_velocity      149885 non-null  float64
 4   ip_address             149873 non-null  object 
 5   user_agent             149887 non-null  object 
 6   email_domain           149910 non-null  object 
 7   phone_number           149873 non-null  object 
 8   billing_city           149884 non-null  object 
 9   billing_postal         149876 non-null  float64
 10  billing_state          149887 non-null  object 
 11  card_bin               149872 non-null  float64
 12  currency               149892 non-null  object 
 13  cvv                    149877 non-null  object 
 14  signature_image        149895 non-nu

In [6]:
# 결측치가 있다.
df.isnull().sum()

account_age_days         108
transaction_amt          130
transaction_adj_amt      114
historic_velocity        115
ip_address               127
user_agent               113
email_domain              90
phone_number             127
billing_city             116
billing_postal           124
billing_state            113
card_bin                 128
currency                 108
cvv                      123
signature_image          105
transaction_type         116
transaction_env          123
EVENT_TIMESTAMP          112
applicant_name           143
billing_address          134
merchant_id              107
locale                   134
tranaction_initiate      126
days_since_last_logon    136
inital_amount            128
EVENT_LABEL                0
dtype: int64

In [13]:
# 결측치의 개수가 적어서 삭제를 진행하기로 한다. - 3천개의 데이터 삭제
df = df.dropna(axis=0)
df.shape

(147000, 26)

In [14]:
# 클래스 불균형 심각
df['EVENT_LABEL'].value_counts()

legit    138996
fraud      8004
Name: EVENT_LABEL, dtype: int64

In [15]:
# 5% 정도가 사기 거래
df['EVENT_LABEL'].value_counts()[1] / len(df) * 100

5.444897959183673

In [16]:
df.describe()

account_age_days  transaction_amt  transaction_adj_amt  \
count     147000.000000    147000.000000        147000.000000   
mean        4645.817224      2521.343592            54.208837   
std         1153.792072       604.680167            10.068128   
min            1.000000         5.000000             1.000000   
25%         3824.000000      2103.000000            48.000000   
50%         4668.000000      2543.000000            55.000000   
75%         5476.000000      2951.000000            61.000000   
max         9119.000000      4999.000000            99.000000   

       historic_velocity  billing_postal       card_bin  \
count      147000.000000   147000.000000  147000.000000   
mean         4702.388673    50179.458129   41834.312320   
std          1188.255402    28389.219411   10082.094148   
min            50.000000      503.000000    6040.000000   
25%          3872.000000    25298.000000   35386.000000   
50%          4729.000000    50072.000000   42086.000000   
75%          5548.000000    74346.000000   47373.000000   
max          9999.000000    99950.000000   67639.000000   

       days_since_last_logon  inital_amount  
count          147000.000000  147000.000000  
mean               49.858524    7996.856367  
std                29.208844    4047.922681  
min                 0.000000    1000.000000  
25%                24.000000    4485.000000  
50%                50.000000    7999.000000  
75%                75.000000   11495.000000  
max               100.000000   15000.000000

In [17]:
# user_agent 특징에서 브라우저 name만 선택해서 진행
df['user_agent'] = df['user_agent'].apply(lambda x: x.split('/')[0])
df.head()

account_age_days  transaction_amt  transaction_adj_amt  historic_velocity  \
0            3371.0           2167.0                 56.0             2572.0   
1            2714.0           2045.0                 48.0             4517.0   
2            6987.0           2892.0                 61.0             5007.0   
3            2712.0           3040.0                 28.0             6022.0   
4            3598.0           2976.0                 66.0             2600.0   

       ip_address user_agent        email_domain           phone_number  \
0   154.68.49.124      Opera     perez-garza.com           878-111-5140   
1   39.131.125.85      Opera   mcneil-ortega.com          (002)736-0139   
2  166.245.194.83    Mozilla  davis-calderon.com      (983)585-2863x652   
3   100.1.217.216    Mozilla        rose-lee.org  +1-678-897-3420x60738   
4  113.156.65.245    Mozilla            nash.net    (013)204-1766x92641   

     billing_city  billing_postal  ... transaction_env      EVENT_TIMESTAMP  \
0      Woodsburgh         96336.0  ...               X  2020-12-29 09:05:51   
1      West Kevin         78083.0  ...               W  2021-06-22 18:05:06   
2     Lorichester         83236.0  ...               X  2021-05-10 13:48:38   
3    Stephenmouth         78364.0  ...               N  2021-03-11 07:36:40   
4  New Brianmouth         77499.0  ...               G  2021-03-27 06:13:35   

    applicant_name    billing_address  merchant_id  locale  \
0     Linda Wright  4684 Sharon Ranch  066-82-8795  niu_NZ   
1     Terri Rivera  7642 Allison Ramp  669-99-9459  apn_IN   
2       Sarah Gray  4948 Lisa Passage  086-41-1624   dv_MV   
3  Valerie Jenkins   1616 Little Camp  669-97-4021  byn_ER   
4      Amy Coleman   149 Harris Rapid  088-21-6329  the_NP   

  tranaction_initiate days_since_last_logon inital_amount EVENT_LABEL  
0                   O                  59.0       13646.0       legit  
1                   J                   0.0       11930.0       legit  
2                   T                  83.0        7412.0       legit  
3                   M                  24.0        4623.0       legit  
4                   K                  21.0        1905.0       legit  

[5 rows x 26 columns]

In [18]:
df['user_agent'].value_counts()

Mozilla    111613
Opera       35387
Name: user_agent, dtype: int64

## 변수(특징) 탐색

In [19]:
df.columns

Index(['account_age_days', 'transaction_amt', 'transaction_adj_amt',
       'historic_velocity', 'ip_address', 'user_agent', 'email_domain',
       'phone_number', 'billing_city', 'billing_postal', 'billing_state',
       'card_bin', 'currency', 'cvv', 'signature_image', 'transaction_type',
       'transaction_env', 'EVENT_TIMESTAMP', 'applicant_name',
       'billing_address', 'merchant_id', 'locale', 'tranaction_initiate',
       'days_since_last_logon', 'inital_amount', 'EVENT_LABEL'],
      dtype='object')

In [29]:
for col in df.columns:
    print(f'{col} - nums : {len(df[col].unique())} EA')
    print(f'{df[col].unique()}')
    print('_'*40)

account_age_days - nums : 6465 EA
[3371. 2714. 6987. ... 1578. 7953. 1533.]
________________________________________
transaction_amt - nums : 3687 EA
[2167. 2045. 2892. ... 4062.  446. 4274.]
________________________________________
transaction_adj_amt - nums : 92 EA
[56. 48. 61. 28. 66. 50. 59. 53. 55. 72. 32. 58. 51. 62. 65. 43. 47. 54.
 70. 46. 39. 63. 57. 45. 44. 64. 35. 52. 60. 34. 69. 41. 68. 38. 37. 42.
 71. 78. 79. 31. 49. 67. 26. 40. 33. 36. 18. 85. 74. 30. 19. 29. 73. 75.
 16. 11. 27. 21. 77. 23. 76. 84. 81. 13. 25. 87. 80. 17. 20. 82. 12. 24.
 83. 22. 15. 86. 92. 10. 88. 89.  1. 14.  7. 93. 91. 90. 95.  9. 99.  5.
 94.  6.]
________________________________________
historic_velocity - nums : 6745 EA
[2572. 4517. 5007. ... 8290. 1851. 1906.]
________________________________________
ip_address - nums : 13633 EA
['154.68.49.124' '39.131.125.85' '166.245.194.83' ... '17.42.89.215'
 '58.244.150.114' '68.177.136.155']
________________________________________
user_agent - nums : 2 E

In [37]:
for col in df.columns:
    print(f'{col} columns', df[col].dtypes)

account_age_days columns float64
transaction_amt columns float64
transaction_adj_amt columns float64
historic_velocity columns float64
ip_address columns object
user_agent columns object
email_domain columns object
phone_number columns object
billing_city columns object
billing_postal columns float64
billing_state columns object
card_bin columns float64
currency columns object
cvv columns object
signature_image columns object
transaction_type columns object
transaction_env columns object
EVENT_TIMESTAMP columns object
applicant_name columns object
billing_address columns object
merchant_id columns object
locale columns object
tranaction_initiate columns object
days_since_last_logon columns float64
inital_amount columns float64
EVENT_LABEL columns object


In [38]:
print(df['user_agent'].dtypes)

object


In [39]:
df['user_agent'].dtypes

dtype('O')

- 연속형/범주형 변수

In [42]:
numeric_lists, categorical_lists = [], []

for col in df.columns:
    if df[col].dtypes == 'O':
        categorical_lists.append(col)
    else:
        numeric_lists.append(col)

print('numeric_lists : ', numeric_lists)
print('categorical_lists : ', categorical_lists)

numeric_lists :  ['account_age_days', 'transaction_amt', 'transaction_adj_amt', 'historic_velocity', 'billing_postal', 'card_bin', 'days_since_last_logon', 'inital_amount']
categorical_lists :  ['ip_address', 'user_agent', 'email_domain', 'phone_number', 'billing_city', 'billing_state', 'currency', 'cvv', 'signature_image', 'transaction_type', 'transaction_env', 'EVENT_TIMESTAMP', 'applicant_name', 'billing_address', 'merchant_id', 'locale', 'tranaction_initiate', 'EVENT_LABEL']


### 연속형 변수(numeric) 탐색

### 범주형 변수(categorical) 탐색